### ISSUE TITLE
just wanna know the THD and the group delay of the codes

### ISSUE THREAD

**Issue by powerpun** [DJ-TOYO/PCM-DSD_Converter#1]
I wanna evaluate this code but need to know more about the THD of the conversion and the group delay.

**Comment by DJ-TOYO** [comment]
I'm Sorry.
I don't speak english.
I don't understand It. "the THD of the conversion and the group delay."

**Comment by powerpun** [comment]
AI translation:
このコードを評価したいのですが、変換のTHDとグループ遅延についてもっと知りたいと思っています。
THDはTotal Harmonic Distortionの略で、信号の歪みを表す指標です。グループ遅延は、入力信号の周波数成分が出力でどれだけ遅れるかを示す指標です。
このコードを評価するには、以下のことを知る必要があります。
• このコードのTHDはどのようになっているか。低歪みであるか、高い周波数で歪みが大きくなっていないか。
• このコードのグループ遅延はどのようになっているか。周波数によって遅延時間が大きく変わらないか。周波数帯域内で一様な遅延時間を実現できているか。
• THDとグループ遅延はこのコードの動作周波数によってどのように変化するか。動作周波数が高いほど影響が出ないか。
• THDとグループ遅延の要件はこのコードにとって重要な要件となっているか。高い精度が求められるアプリケーションに適したコードとなっているか。
これらの点を確認できれば、このコードの評価をより適切に行うことができると思います。ご質問等ありましたらお気軽にご連絡ください。

**Comment by powerpun** [comment]
C1900 II mismatch between 'P1' version '20221215' and 'P2' version '20220715'
could you please tell me what version is your visual studio?

**Comment by powerpun** [comment]
C1900 II 'P1' バージョン '20221215' と 'P2' バージョン '20220715' の間に不一致があります。
ご使用のVisual Studioのバージョンを教えていただけますか?

**Comment by DJ-TOYO** [comment]
> ご使用のVisual Studioのバージョンを教えていただけますか?

Microsoft Visual Studio Community 2022
Version 17.6.0
VisualStudio.17.Release/17.6.0+33712.159
Microsoft .NET Framework
Version 4.8.09032

インストールされているバージョン:Community

Visual C++ 2022   00482-90000-00000-AA176
Microsoft Visual C++ 2022

**Comment by DJ-TOYO** [comment]
> AI translation: このコードを評価したいのですが、変換のTHDとグループ遅延についてもっと知りたいと思っています。 THDはTotal Harmonic Distortionの略で、信号の歪みを表す指標です。グループ遅延は、入力信号の周波数成分が出力でどれだけ遅れるかを示す指標です。 このコードを評価するには、以下のことを知る必要があります。 • このコードのTHDはどのようになっているか。低歪みであるか、高い周波数で歪みが大きくなっていないか。 • このコードのグループ遅延はどのようになっているか。周波数によって遅延時間が大きく変わらないか。周波数帯域内で一様な遅延時間を実現できているか。 • THDとグループ遅延はこのコードの動作周波数によってどのように変化するか。動作周波数が高いほど影響が出ないか。 • THDとグループ遅延の要件はこのコードにとって重要な要件となっているか。高い精度が求められるアプリケーションに適したコードとなっているか。 これらの点を確認できれば、このコードの評価をより適切に行うことができると思います。ご質問等ありましたらお気軽にご連絡ください。

DSD変換した信号の精度を知りたいのでしょうか？
私は作者に承諾を得てDSD変換ロジックのC++ソースを利用しています。
製作者の機能はWAV to DFF変換のみです。
私は、様々なフォーマット、タグ対応、DSFファイル対応しました。
DSD変換アルゴリズムは不具合を直しただけです。
信号精度については私は分かりません。
製作者（本人）のサイトを参照下さい。
性能比較グラフが掲載されております。
https://pcmdsd.com/Software/PCM-DSD_Converter.html

**Comment by powerpun** [comment]
情報をありがとう、私はそれを見ました、変換パフォーマンスはかなり良いです。 戻って、あなたが変更したものを比較します、もう一度ありがとう。

**Comment by DJ-TOYO** [comment]
それは良かったです。
ありがとうございました。
本件について解決したと思いますのでクローズします。
